config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root 'home#index'

  get '/faqs', to: 'home#faqs', as: :faqs
  get '/about_us', to: 'home#about_us', as: :about_us
  get '/contact_us', to: 'home#contact_us', as: :contact_us

  get '/ingredients', to: 'ingredients#index', as: :ingredients
  post '/find_ingredient', to: 'ingredients#find_ingredient', as: :find_ingredient
  post '/update_inventory', to: 'ingredients#update_inventory', as: :update_inventory
  post '/create_price', to: 'ingredients#create_price', as: :create_price
  post '/get_price', to: 'ingredients#get_price', as: :get_price
  post '/get_ingredients_from_usda', to: 'ingredients#get_ingredients_from_usda', as: :get_ingredients_from_usda

  post '/get_units_from_usda', to: 'units#get_units_from_usda', as: :get_units_from_usda
  post '/get_units_by_ingredient', to: 'units#get_units_by_ingredient', as: :get_units_by_ingredient
  post '/create_units', to: 'units#create_units', as: :create_units

  resources :recipes do
    post 'clone'
    get :autocomplete_ingredient_name, on: :collection
  end
  get '/filter_recipes', to: 'recipes#filter_recipes', as: :filter_recipes
  post '/get_type_of_unit', to: 'recipes#get_type_of_unit', as: :get_type_of_unit
  get '/nutrition_label', to: 'recipes#nutrition_label', as: :nutrition_label
  post '/get_recipe_by_id', to: 'recipes#get_recipe_by_id', as: :get_recipe_by_id
  post '/search_tags', to: 'recipes#search_tags', as: :search_tags

  get '/profile', to: 'profile#index', as: :profile
  
  resources :groups
  post '/group_filter_recipes', to: 'groups#filter_recipes', as: :group_filter_recipes
end

app/models/recipe.rb
# Recipe model
class Recipe < ActiveRecord::Base
  belongs_to :user
  has_many :ingredient_quantities,
           class_name: 'RecipeIngredientsQuantity',
           dependent: :destroy
  has_many :ingredients, through: :ingredient_quantities
  has_and_belongs_to_many :meal_components
  has_and_belongs_to_many :meal_categories
  has_and_belongs_to_many :tags
  has_many :group_recipes_quantities, dependent: :destroy

  accepts_nested_attributes_for :ingredient_quantities,
                                reject_if: :all_blank,
                                allow_destroy: true
  accepts_nested_attributes_for :ingredients

  validates_presence_of :name, :servings_count

  scope :by_categories, -> (ids) { includes(:meal_categories).where(meal_categories: { id: ids }) }
  scope :by_components, -> (ids) { includes(:meal_components).where(meal_components: { id: ids }) }
  scope :by_tags, -> (ids) { includes(:tags).where(tags: {id: ids}) }
  scope :in_group, -> (id) { includes(:group_recipes_quantities).where(group_recipes_quantities: { group_id: id }) }

  def update_categories(categories)
    for_delete = meal_categories - categories
    for_delete.each { |c| meal_categories.delete(c) }
    categories.each do |c|
      meal_categories.append(c) unless meal_categories.find_by(id: c.id)
    end
  end

  def update_components(components)
    for_delete = meal_components - components
    for_delete.each { |c| meal_components.delete(c) }
    components.each do |c|
      meal_components.append(c) unless meal_components.find_by(id: c.id)
    end
  end

  def update_tags(tags)
    for_delete = self.tags - tags
    for_delete.each do |t|
      self.tags.delete(t)
      t.destroy if t.recipes.blank?
    end
    tags.each do |tag|
      self.tags.append(tag) unless self.tags.find_by(id: tag.id)
    end
  end

  def create_coefficients_for_usda_ingredients
    ingredients.each(&:create_coefficients)
  end
end

app/controllers/recipes_controller.rb
# Actions for recipes
class RecipesController < ApplicationController
  load_and_authorize_resource
  autocomplete :ingredient, :name, extra_data: [:store, :usda_id, :unit_type_id]
  before_action :set_recipe, only: [:edit, :update, :destroy]
  before_action :set_items_for_recipe, only: [:new, :edit, :update, :create]

  def index
    @recipes = current_user.recipes.order(:name)
    filtering_params(params).each do |key, value|
      @recipes = @recipes.public_send(key, value) if value.present?
    end
    @categories = MealCategory.where.not(id: params[:by_categories]).order(:name)
    @selected_categories = MealCategory.where(id: params[:by_categories])
    @tags = current_user.tags.where.not(id: params[:by_tags]).order(:name)
    @selected_tags = Tag.where(id: params[:by_tags])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    recipe = Recipe.new(recipe_params)
    recipe.user = current_user
    if recipe.save
      recipe.create_coefficients_for_usda_ingredients
      recipe.meal_categories << MealCategory.where(id: params[:categories]) if params[:categories]
      recipe.meal_components << MealComponent.where(id: params[:components]) if params[:components]
      recipe.tags << tags_from_string(params[:tags]) if params[:tags]
      redirect_to recipes_path
    else
      render :new
    end
  end

  def edit
    @tags = @recipe.tags
  end

  def update
    @recipe.update_categories(MealCategory.where(id: params[:categories]))
    @recipe.update_components(MealComponent.where(id: params[:components]))
    @recipe.update_tags(tags_from_string(params[:tags]))
    if @recipe.update_attributes(recipe_params)
      @recipe.create_coefficients_for_usda_ingredients
      redirect_to recipes_path
    else
      render :edit
    end
  end

  def destroy
    tag_ids = @recipe.tags.map(&:id)
    if @recipe.try(:destroy)
      Tag.where(id: tag_ids).each do |tag|
        tag.destroy if tag.recipes.count == 0
      end
    end
    render json: { status: 'success' }
  end

  def nutrition_label
    ingredients = params[:ingredients]
    count = params[:count].to_i

    @serving_size = @calories = @cholesterol = @sodium = @carbohydrate =
      @fiber = @sugars = @protein = @fats = @saturated_fats = 0

    for i in count.times
      unit = ingredients[i.to_s][:unit]
      usda_id = ingredients[i.to_s][:usda_id]
      quantity = ingredients[i.to_s][:quantity]

      if unit == 'gram'
        coefficient = 1
      else
        coefficient = UsdaNutrientDatabase::Food.find_by(nutrient_databank_number: usda_id).weights.where(measurement_description: unit).first.gram_weight
      end
      quantity_in_grams = quantity.to_f * coefficient
      nutrients = UsdaNutrientDatabase::FoodsNutrient.where(nutrient_databank_number: usda_id)
      @serving_size += quantity_in_grams
      @calories += calculate_nutrient(nutrients, 'Energy', quantity_in_grams)
      @cholesterol += calculate_nutrient(nutrients, 'Cholesterol', quantity_in_grams)
      @sodium += calculate_nutrient(nutrients, 'Sodium, Na', quantity_in_grams)
      @carbohydrate += calculate_nutrient(nutrients, 'Carbohydrate, by difference', quantity_in_grams)
      @fiber += calculate_nutrient(nutrients, 'Fiber, total dietary', quantity_in_grams)
      @sugars += calculate_nutrient(nutrients, 'Sugars, total', quantity_in_grams)
      @protein += calculate_nutrient(nutrients, 'Protein', quantity_in_grams)
      @fats += calculate_nutrient(nutrients, 'Total lipid (fat)', quantity_in_grams)
      @saturated_fats += calculate_nutrient(nutrients, 'Fatty acids, total saturated', quantity_in_grams)
    end
    @amount_per_serving = '?'

    render pdf: 'file_name',
           template: 'recipes/nutrition_label.html.erb'
  end

  def calculate_nutrient(nutrients, name, quantity)
    nutrient = nutrients.includes(:nutrient).where(usda_nutrients: { nutrient_description: name }).first
    nutrient_value = nutrient ? nutrient.nutrient_value : 0
    nutrient_in_gram = nutrient_value / 100
    return nutrient_in_gram * quantity
  end

  def clone
    original_recipe = Recipe.find(params[:recipe_id])
    new_recipe = original_recipe.dup
    new_recipe.name += ' Copy'
    new_recipe.save
    original_recipe.ingredient_quantities.each do |iq|
      new_iq = iq.dup
      new_recipe.ingredient_quantities << new_iq
    end
    original_recipe.tags.each do |tag|
      new_recipe.tags << tag
    end
    original_recipe.meal_components.each do |c|
      new_recipe.meal_components << c
    end
    original_recipe.meal_categories.each do |c|
      new_recipe.meal_categories << c
    end
    redirect_to recipes_path
  end

  def filter_recipes
    category_ids = params[:categories] ? params[:categories] : []
    tags_ids = params[:tags] ? params[:tags] : []
    if params[:category_id].present?
      category_ids.push params[:category_id]
    elsif params[:tag_id].present?
      tags_ids.push params[:tag_id]
    end
    redirect_to recipes_path(by_categories: category_ids, by_tags: tags_ids)
  end

  def get_type_of_unit
    unit = Unit.find_by(id: params[:unit_id])
    render json: { type: unit.unit_type_id }
  end

  def get_autocomplete_items(parameters)
    items = active_record_get_autocomplete_items(parameters)
    items = items.where(user: current_user)
  end

  def get_recipe_by_id
    recipe = Recipe.find_by(id: params[:recipe_id])
    render json: { recipe: recipe }
  end

  def search_tags
    tags = current_user.tags.where('name ILIKE ?', "%#{params[:name]}%").pluck(:name)
    render json: { tags: tags }
  end

  private

  def tags_from_string(str)
    names = str.split(', ')
    tags_id = []
    names.each do |t|
      tags_id << Tag.find_or_create_by(name: t.downcase, user_id: current_user.id).id
    end
    Tag.where(id: tags_id)
  end

  def set_recipe
    @recipe = Recipe.find_by(id: params[:id])
  end

  def set_items_for_recipe
    @units = Unit.all.order(:unit_type_id)
    @meal_categories = MealCategory.all
    @meal_components = MealComponent.all
  end

  def recipe_params
    params.require(:recipe).permit(
      :name,
      :servings_count,
      :instruction,
      ingredient_quantities_attributes: [
        :id,
        :quantity,
        :ingredient_id,
        :recipe_id,
        :unit_id,
        :_destroy,
        ingredient_attributes: [
          :id,
          :name,
          :store,
          :user_id,
          :unit_type_id,
          :usda_id
        ]
      ]
    )
  end

  def filtering_params(params)
    params.slice(:by_tags, :by_categories)
  end
end

app/views/recipes/_ingredient_quantity_fields.html.erb
<tr>
  <%= f.fields_for :ingredient do |ingredient| %>
    <%= ingredient.hidden_field :user_id, value: current_user.id %>
    <td>
      <%= f.text_field :quantity, class: 'qty', required: true, pattern: '[0-9]+([,\.][0-9]+)?' %>
    </td>

    <%= ingredient.hidden_field :unit_type_id, {
          value: ingredient.object.unit_type.present? ? ingredient.object.unit_type_id : UnitType.first.id,
          class: 'ingredient_unit_type' } %>

    <td class="unit-select-wrap">
      <div class="select-wrap">
        <% units = ingredient.object.unit_type.present? ? ingredient.object.get_units : @units %>
        <%= f.select :unit_id,
              options_for_select(units.collect { |c| [c.name, c.id] }, selected: f.object.unit_id),
              { include_blank: true }, class: 'units unit_select', required: true %>
      </div>
    </td>

    <td class="ingredient-name-wrap">
      <%= ingredient.autocomplete_field :name, autocomplete_ingredient_name_recipes_path, class: 'autocomplete-name ingredient_name', required: true, title: 'Can\'t change' %>
    </td>

    <td class="store-wrap">
      <%= ingredient.text_field :store, class: 'store', 'data-tooltip' => 'tooltip', title: 'Can\'t change' %>
    </td>
    <td class="usda-wrap" >
      <button type="button" name="button" class="glass<%= ' set' if ingredient.object.usda_id.present? %>" data-toggle="modal" data-target="#nutrient_Modal" data-tooltip="tooltip" title="Can't change">
      </button>
      <div class="clickable">
      </div>
      <%= ingredient.hidden_field :usda_id, { value: ingredient.object.usda_id, class: 'ingredient_usda_id' } %>
    </td>
  <% end %>
  <td>
    <%= link_to_remove_association 'remove', f %>
  </td>
</tr>

<script type="text/javascript">
  $('.autocomplete-name').off('change');
  $('.autocomplete-name').on('change', function() {
    var self = $(this);
    $.ajax({
      url: '<%= find_ingredient_path %>',
      type: 'POST',
      data: {
        user_id: '<%= current_user.id %>',
        ingredient_name: self.val()
      },
      success: function(response) {
        if (response.ingredient == null || response.ingredient == '') {

          var store = self.parent().siblings('.store-wrap').children('.store').prop('disabled', false);

          var usda_wrap = self.parent().siblings('.usda-wrap');
          usda_wrap.children('.ingredient_usda_id').val('');
          var glass = usda_wrap.children('.glass');
          glass.removeClass('set');
          glass.prop('disabled', false);

          return;
        }

        self.parent().siblings('.ingredient_unit_type').val(response.ingredient.unit_type_id);

        if (response.units !== null && response.units !== '') {
          var unit_select = self.parent().siblings('.unit-select-wrap').children('.select-wrap').children('.unit_select');
          unit_select.find('option').remove();
          response.units.forEach(function(u) {
            var option = $('<option></option>', {'value': u.id, 'text': u.name});
            unit_select.append(option);
          });
        }

        var store = self.parent().siblings('.store-wrap').children('.store');
        store.val(response.ingredient.store);
        store.prop('disabled', true);

        var usda_wrap = self.parent().siblings('.usda-wrap');
        usda_wrap.children('.ingredient_usda_id').val(response.ingredient.usda_id);
        var glass = usda_wrap.children('.glass');
        if (response.ingredient.usda_id !== '' && response.ingredient.usda_id !== null) {
          glass.addClass('set');
          glass.prop('disabled', true);
        } else {
          glass.removeClass('set');
          glass.prop('disabled', false);
        }
      }
    });
  });

  $('.autocomplete-name').unbind('railsAutocomplete.select');
  $('.autocomplete-name').bind('railsAutocomplete.select', function(event, data){

    $(this).parent().siblings('.ingredient_unit_type').val(data.item.unit_type_id);
    var unit_select = $(this).parent().siblings('.unit-select-wrap').children('.select-wrap').children('.unit_select');
    $.ajax({
      url: '<%= get_units_by_ingredient_path %>',
      type: 'POST',
      data: {
        ingredient_name: data.item.label
      },
      success: function(response) {
        unit_select.find('option').remove();
        response.units.forEach(function(u) {
          var option = $('<option></option>', {'value': u.id, 'text': u.name});
          unit_select.append(option);
        });
      }
    });

    var store = $(this).parent().siblings('.store-wrap').children('.store');
    store.val(data.item.store);
    store.prop('disabled', true);

    var usda_wrap = $(this).parent().siblings('.usda-wrap');
    usda_wrap.children('.ingredient_usda_id').val(data.item.usda_id);
    var glass = usda_wrap.children('.glass');
    if (data.item.usda_id !== "" && data.item.usda_id !== null) {
      glass.addClass('set');
      glass.prop('disabled', true);
    } else {
      glass.removeClass('set');
      glass.prop('disabled', false);
    }

  });

  $('.remove_fields.dynamic').off('click');
  $('.remove_fields.dynamic').on('click', function() {
    var row = $(this).parents('tr');
    row.animate({ opacity: '0' }, 200);
    setTimeout(function() {
      row.css('height', '52px');
      row.children().css('display', 'none');
      row.animate({ height: '0px' }, 200);
    }, 200);
    setTimeout(function() {
      row.remove();
    }, 400);
  });

  $(".qty").keypress(function (event) {
    if ((event.which != 46 || $(this).val().indexOf('.') != -1) && (event.which < 48 || event.which > 57)) {
      return false;
    }
  });

  $('.unit_select').on('change', function() {
    var unit_type = $(this).parents('tr').children('.ingredient_unit_type');
    var unit_select = $(this).find(':selected').val();
    $.ajax({
      url: '/get_type_of_unit',
      data: {
        'unit_id': unit_select
      },
      type: 'post',
      success: function(data){
        unit_type.val(data.type);
      }
    });
  });
</script>

app/views/recipes/_remove_confirmation.html.erb
<div id="remove_confirmation_Modal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-md">

    <div class="modal-content">
      <div class="modal-header">
        <!-- <span>Warning</span> -->
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <div class="modal-body col-centered">
        <p>
          Are you sure you want to delete this recipe?
        </p>
        <div class="confirm_cancel_buttons">
          <button id="submit" class="confirm_button" data-dismiss="modal">Delete</button>
          <button id="submit" class="cancel_button" data-dismiss="modal">Cancel</button>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/recipes/_save_changes_confirmation.html.erb
 <div id="save_changes_confirmation_Modal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-md">

    <div class="modal-content">
      <div class="modal-header">
        <!-- <span>Warning</span> -->
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <div class="modal-body col-centered">
        <p>
          Do you want to save changes?
        </p>
        <div class="confirm_cancel_buttons">
          <button id="submit" class="cancel_button" data-dismiss="modal">Yes</button>
          <button id="submit" class="confirm_button" data-dismiss="modal">No</button>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/recipes/_usda_ingredients.html.erb
<div id="nutrient_Modal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header" >
        <div class = "header-search">
          <input type="text" class="form-control inputs" placeholder="search" id="search_usda_input" data-toggle="tooltip" data-placement="top" title="Enter more charachters!">
          <span></span>
        </div>
        <span>USDA nutrient data</span>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body" >
        <table class="table" id="glass_table">
          <col style="width:20%">
          <col style="width:40%">
          <col style="width:40%">
          <thead>
            <tr>
              <th>
                NDB No.
              </th>
              <th>
                DESCRIPTION
              </th>
              <th>
                FOOD GROUP
              </th>
            </tr>
          </thead>
          <tbody>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
$(document).ready(function() {

  $(".ingredients").on("click", ".glass", function(){
    var glass_btn = $(this); // кнопочка usda
    var usda_id = $(this).parent("td").children(".ingredient_usda_id"); // прихований інпут інгредієнта для usda
    var name_elem = $(this).parents("tr").find(".ingredient_name"); // назва інгредієнту
    var unit_select = $(this).parents("tr").find(".unit_select"); // селект для юнітів
    var unit_type = $(this).parents("tr").find(".ingredient_unit_type"); // хіден для типу юніта
    var usda_units = $(this).parents("tr").find(".usda_units"); // всі доступні usda юніти

    $('#nutrient_Modal').on('show.bs.modal',function(){
      $('#search_usda_input').val(name_elem.val());
    });

    var new_name = name_elem.val();
    new_name=new_name.replace(/[^A-Z0-9\s]/gi, "").replace(/\s\s+/g, ' ');
    new_name=$.trim(new_name);
    if(new_name.length > 2) {
      update_usda_table(new_name, glass_btn, usda_id, unit_select, unit_type);
    }

    $('#search_usda_input').on('change', function(){
      var new_name = $(this).val();
      new_name=new_name.replace(/[^A-Z0-9\s]/gi, "").replace(/\s\s+/g, ' ');
      new_name=$.trim(new_name);
      if(new_name.length > 2){
        update_usda_table(new_name, glass_btn, usda_id, unit_select, unit_type);
        $(this).tooltip('hide');
      } else{
        $(this).tooltip('show');
      }
    });
  });

  function update_usda_table(name, glass_btn, usda_id, unit_select, unit_type){
    $.ajax({
      url: '/get_ingredients_from_usda',
      data: {
        'name': name
      },
      type: 'post',
      success: function (data) {
        $('#glass_table').find("tr:gt(0)").remove();
        for (var i in data.food) {
          $('#glass_table tbody').append(
            $('<tr/>', {
              'class': (usda_id.val() == data.food[i].nutrient_databank_number ? 'usda_id_checked' : ''),
              'data-num': data.food[i].nutrient_databank_number
            }).append(
              $('<td/>', {
                  'text': data.food[i].nutrient_databank_number
              }),
              $('<td/>', {
                'text': data.food[i].short_description
              }),
              $('<td/>', {
                'text': data.food[i].food_group.description
              })
            )
          );
        }
        $('#glass_table tbody tr').on("click", function () {
          var nutrient_databank_number = $(this).children("td:first-child").text();
          usda_id.val(nutrient_databank_number);
          $.ajax({
            url: '/get_units_from_usda',
            data: {
              'id': nutrient_databank_number
            },
            type: 'post',
            success: function (data) {
              unit_select.find('option').remove();
              for (var i in data.units) {
                unit_select.append(new Option(data.units[i].name, data.units[i].id));
              }
              unit_type.val(<%= UnitType.find_by(name: 'USDA').id %>);
            }
          });
          $('#nutrient_Modal').modal('hide');
          glass_btn.css({"background-color": "#C3D1C7", "border-radius": "3px"});
        });
      }
    });
  }
});
</script>

app/views/recipes/edit.html.erb
<%= render '/layouts/header' %>

<div class="cont">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="edit-recipe">
      <h1>Edit recipe</h1>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. <br>
        Proin et porta nunc. In aliquam lacinia ullamcorper.
      </p>

      <%= render 'form' %>
      <%= render 'usda_ingredients' %>

    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<%= render '/layouts/header' %>
<!-- <link href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet"> -->

<div class="cont">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="recipes-wrap">
      <h1>My recipes</h1>
      <p>
        It all starts here! Manage and create all of your recipes below.<br>
		    Use the "Category" and "Tag" filters to quickly find the recipe you're looking for.
      </p>
      <section class="col-md-12 col-sm-12 col-xs-12 recipes-nav">
        <%= form_tag  '/filter_recipes', method: :get do %>
          <div class="row" style="margin:0;">
            <div class="add-recipe">
              <%= link_to new_recipe_path do %>
                <span class="plus"></span>
                <span id="span-add">ADD RECIPE</span>
              <% end %>
            </div>

            <div class="filters">
              <div class="select-wrapper">
                <%= select_tag 'category_id', options_for_select(@categories.all.collect{ |c| [c.name, c.id] }), include_blank: 'Category', id: 'category_select' %>
              </div>
              <div class="select-wrapper">
                <%= select_tag 'tag_id', options_for_select(@tags.all.collect{ |c| [c.name, c.id] }), include_blank: 'Tag', id: 'tag_select' %>
              </div>
            </div>
          </div>
          <div class="row" style="margin:0;">
            <div class="input_filters">
              <% if @selected_categories.present? %>
                <div>
                  <span class="selected_title">Selected categories:</span>
                  <% @selected_categories.each do |category| %>
                    <span class="value" id="<%= category.id %>"><%= category.name %>
                      <span class="glyphicon glyphicon-remove remove_category"></span>
                      <%= hidden_field_tag 'categories[]', category.id %>
                    </span>
                  <% end %>
                </div>
              <% end %>
              <% if @selected_tags.present? %>
                <div>
                  <span class="selected_title">Selected tags:</span>
                  <% @selected_tags.each do |tag| %>
                    <span class="value" id="<%= tag.id %>"><%= tag.name %>
                      <span class="glyphicon glyphicon-remove remove_tag"></span>
                      <%= hidden_field_tag 'tags[]', tag.id %>
                    </span>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </section>

      <section class="recipes-list">
        <table class="table" id="table_recipes">
          <col style="width:60%">
          <col style="width:30%">
          <col style="width:10%">
          <% @recipes.each do |recipe| %>
            <tr>
              <td><%= recipe.name %></td>
              <td>
                <%= link_to 'Edit', edit_recipe_path(recipe.id) %>
                <span class="devider">/</span>
                <%= link_to 'Delete', '#', class: 'delete_link', 'data-id' => recipe.id %>
              </td>
              <td>
                <%= link_to recipe_clone_path(recipe.id), method: :post do %>
                  <i class="icon_files" data-toggle="tooltip" title="Clone" ></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </table>
      </section>
    </div>
  </div>
</div>

<%= render 'remove_confirmation' %>

<script type="text/javascript">
$(document).ready(function() {
  $("[href='/recipes']").addClass("active");

  $("#category_select").change(function() {
    $(this).parents("form").submit();
  });

  $("#tag_select").change(function() {
    $(this).parents("form").submit();
  });

  $(".remove_category, .remove_tag").on("click", function(){
    var parent = $(this).parents(".value");
    var form = $(this).parents("form");
    parent.remove();
    form.submit();
  });

  $('.delete_link').on('click', function(e) {
    e.preventDefault();

    var row = $(this).parents('tr');
    var id = $(this).data('id');

    $('.confirm_button').off('click');
    $('.confirm_button').on('click', function functionName() {
      $.ajax({
        method: 'DELETE',
        url: '<%= recipes_path %>' + '/' + id
      }).done(function() {
        row.remove();
      });
    });

    $('#remove_confirmation_Modal').modal();
  });
});

</script>

app/views/recipes/new.html.erb
<%= render '/layouts/header' %>

<div class="cont">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="new-recipe">
      <h1>Add recipe</h1>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. <br>
        Proin et porta nunc. In aliquam lacinia ullamcorper.
      </p>

      <%= render 'form' %>
      <%= render 'usda_ingredients' %>

    </div>
  </div>
</div>