config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root 'home#index'

  get '/faqs', to: 'home#faqs', as: :faqs
  get '/about_us', to: 'home#about_us', as: :about_us
  get '/contact_us', to: 'home#contact_us', as: :contact_us

  get '/ingredients', to: 'ingredients#index', as: :ingredients
  post '/find_ingredient', to: 'ingredients#find_ingredient', as: :find_ingredient
  post '/update_inventory', to: 'ingredients#update_inventory', as: :update_inventory
  post '/create_price', to: 'ingredients#create_price', as: :create_price
  post '/get_price', to: 'ingredients#get_price', as: :get_price
  post '/get_ingredients_from_usda', to: 'ingredients#get_ingredients_from_usda', as: :get_ingredients_from_usda

  post '/get_units_from_usda', to: 'units#get_units_from_usda', as: :get_units_from_usda
  post '/get_units_by_ingredient', to: 'units#get_units_by_ingredient', as: :get_units_by_ingredient
  post '/create_units', to: 'units#create_units', as: :create_units

  resources :recipes do
    post 'clone'
    get :autocomplete_ingredient_name, on: :collection
  end
  get '/filter_recipes', to: 'recipes#filter_recipes', as: :filter_recipes
  post '/get_type_of_unit', to: 'recipes#get_type_of_unit', as: :get_type_of_unit
  get '/nutrition_label', to: 'recipes#nutrition_label', as: :nutrition_label
  post '/get_recipe_by_id', to: 'recipes#get_recipe_by_id', as: :get_recipe_by_id
  post '/search_tags', to: 'recipes#search_tags', as: :search_tags

  get '/profile', to: 'profile#index', as: :profile
  
  resources :groups
  post '/group_filter_recipes', to: 'groups#filter_recipes', as: :group_filter_recipes
end

app/models/group.rb
# Group model
class Group < ActiveRecord::Base
  belongs_to :user
  has_many :recipe_quantities, class_name: 'GroupRecipesQuantity', dependent: :destroy
  has_many :recipes, through: :recipe_quantities
  has_many :appetite_size_quantities, dependent: :destroy
  has_many :appetite_sizes, through: :appetite_size_quantities

  accepts_nested_attributes_for :appetite_size_quantities, reject_if: proc { |attributes| attributes[:quantity].blank? || attributes[:quantity] == 0 }, allow_destroy: true
  accepts_nested_attributes_for :recipe_quantities, reject_if: proc { |attributes| attributes[:quantity].blank? || attributes[:quantity] == 0 }, allow_destroy: true

  validates_presence_of :name

  def with_size(size)
    asq = self.appetite_size_quantities.find_by(appetite_size: size)
    asq = size.appetite_size_quantities.build unless asq.present?
    asq
  end

  def with_recipe(recipe)
    rq = self.recipe_quantities.where(recipe: recipe)
    rq = recipe.group_recipes_quantities.build unless rq.present?
    rq
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :set_items, only: [:new, :edit]

  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def create
    group = Group.new(group_params)
    group.user = current_user
    if group.save
      group.total_individuals = group.appetite_size_quantities.sum(:quantity)
      group.total_servings = 0
      group.appetite_sizes.each do |size|
        group.total_servings += group.appetite_size_quantities.find_by(appetite_size: size).quantity * size.coefficient
      end
      group.save

      redirect_to groups_path
    else
      render :new
    end
  end

  def edit
    @group_recipes = @group.recipes
    @recipes = @recipes - @group_recipes
  end

  def update
    if @group.update_attributes(group_params)
      redirect_to groups_path
    else
      render :edit
    end
  end

  def destroy
    @group.try(:destroy)
    render json: { status: 'success' }
  end

  def show
    @group_recipes = @group.recipe_quantities
    recipe_ingredients = RecipeIngredientsQuantity.where(recipe_id: @group.recipes.map(&:id))
    @ingredients = recipe_ingredients.map(&:ingredient).uniq
  end

  def filter_recipes
    categories = MealCategory.where(name: params[:categories])
    components = MealComponent.where(name: params[:components])
    recipes = current_user.recipes
    recipes = recipes.by_categories(categories.map(&:id)) if categories.present?
    recipes = recipes - recipes.by_components(components.map(&:id)) if components.present?
    render json: { recipes: recipes }
  end

  private

  def set_group
    @group = Group.find_by(id: params[:id])
  end

  def set_items
    @appetite_sizes = AppetiteSize.all
    @recipes = current_user.recipes.includes(:group_recipes_quantities).order('group_recipes_quantities.quantity')
    @components = MealComponent.all
    @categories = MealCategory.all
  end

  def group_params
    params.require(:group).permit(
      :name,
      :description,
      appetite_size_quantities_attributes: [
        :id,
        :quantity,
        :appetite_size_id,
        :group_id
      ],
      recipe_quantities_attributes: [
        :id,
        :quantity,
        :individuals_served,
        :recipe_id,
        :group_id,
        :_destroy
      ]
    )
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for @group, html: { id: 'new_group', multipart: true } do |f| %>
  <div class="meal_plan-inputs">
    <%= f.text_field :name, class: 'form-control inputs', id: 'group-name', placeholder: 'Group name', required: true %>
    <div id="meal_plan-inputs-inside">
      <% for a_size in @appetite_sizes %>
        <%= f.fields_for :appetite_size_quantities, @group.with_size(a_size) do |asq| %>
          <div>
            <label>Number of <%= a_size.name %> appetite individuals(<%= a_size.coefficient.to_s %> Serving/Meal):</label>
            <%= asq.text_field :quantity, class: 'form-control inputs app-size', placeholder: '0', 'data-coeff' => a_size.coefficient %>
            <%= asq.hidden_field :appetite_size_id, value: a_size.id %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="total">
      <div><span class="total-label">TOTAL INDIVIDUALS</span><span class="quantity"><%= f.object.total_individuals %></span></div>
      <div><span class="total-label">TOTAL SERVINGS</span><span class="quantity"><%= f.object.total_servings %></span></div>
    </div>
    <%= f.text_area :description, placeholder: 'Describe any group-specific meal or purchasing instructions here', class: 'form-control' %>
  </div>

  <hr id="horizontal-line">

  <div class="col-md-12 col-sm-12 col-xs-12 meal_plan-content">
    <div class="content-meal">

      <div class="select-wrapper" id="first_sel">
        <%= select_tag 'category_id', options_for_select(@categories.all.collect{ |c| [c.name, c.id] }), include_blank: 'Categories', id: 'category_filter' %>
      </div>
      <div class="select-wrapper" id="second_sel">
        <%= select_tag 'component_id', options_for_select(@components.all.collect{ |c| [c.name, c.id] }), include_blank: 'Hide meals that contain', id: 'component_filter' %>
      </div>
      <div class="select-wrapper" id="third_sel">
        <%= select_tag 'recipes', options_for_select(@recipes.collect{ |c| [c.name, c.id] }), include_blank: 'Recipes', id: 'recipes_select' %>
      </div>

      <div class="input_filters move-left">
        <div id="selected_categories">
          <span class="selected_title" style="display: none;">Selected categories:</span>
        </div>
        <div id="selected_components">
          <span class="selected_title" style="display: none;">Hide meals that contain:</span>
        </div>
      </div>
      <div class = table-scroll>
        <table id="table_meals" class="table">
          <col style="width:15%">
          <col style="width:45%">
          <col style="width:35%">
          <col style="width:5%">
          <thead>
          <tr>
            <th>#of times served</th>
            <th>RECIPE</th>
            <th>#number of individuals served</th>
            <th>#</th>
          </tr>
          </thead>
          <tbody>
            <% if @group.persisted? %>
              <% for recipe in @group_recipes %>
                <%= f.fields_for :recipe_quantities, @group.with_recipe(recipe) do |rq| %>
                  <tr id="<%= recipe.id %>">
                    <td>
                      <%= rq.text_field :quantity, class: 'recipe_quantity' %>
                      <%= rq.hidden_field :recipe_id, value: recipe.id %>
                    </td>
                    <td class="recipe_name">
                      <%= recipe.name %>
                    </td>
                    <td>
                      <%= rq.text_field :individuals_served, class: 'range',
                                        'data-slider-id' => 'ex1Slider',
                                        'data-slider-min' => '0',
                                        'data-slider-max' => f.object.total_individuals ? f.object.total_individuals : '20',
                                        'data-slider-value' => rq.object.individuals_served ? rq.object.individuals_served : '0',
                                        'data-slider-step' => '1' %>
                    </td>
                    <td>
                      <%= link_to 'remove' %>
                    </td>
                  </tr>
                <% end %>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <%= f.submit 'SAVE MEAL PLAN & CREATE SHOPPING LIST', class: 'submit-button make-thiner' %>
<% end %>

<script type="text/javascript">
$(document).ready(function () {
  $(".range").slider({
    tooltip: 'always',
    formatter: function(value) {
      return value;
    }
  });

////////////////////////// INPUT VALIDATION //////////////////
  $('#meal_plan-inputs-inside').find('input').keypress(function (e) {
    //if the letter is not digit then display error and don't type anything
    if (this.value.length == 0 && e.which == 48 ){
      return false;
    }
    if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
      return false;
    }
  });

/////////////////////////// TOTAL LOGIC //////////////////////
  $('#meal_plan-inputs-inside').on('keyup','input',function(){
    var sum = 0;
    var servings = 0;
    $('.app-size').each(function(){
      if($(this).val().length !== 0){
        sum += parseInt($(this).val());
        servings += ($(this).attr('data-coeff')*$(this).val());
      }
    });
    $('.quantity').first().text(sum);
    $('.quantity').last().text(servings);

    $.each($(".range"), function(elem, index){ ////////////////////// not working !!!!!!!!!!!!!!!!!!!!!
      if($(elem).attr('data-slider-value') > sum){
        $(elem).attr('data-slider-value', sum);
      }
      $(elem).attr('data-slider-max', sum);
    });

  ///////////////////// ENABLE\DISABLE NEXT BUTTON //////////////////
    if($('.quantity').first().text() !== '0'){
      $('.next').attr('disabled',false);
      $('.next').hover(function(){
        $(this).css("background-color", "#DE993C");
      },function () {
        $(this).css('background-color', '#EFA94A')
      });
    }
  });

////////////////////////////// FILTERING ////////////////////////////////
  $('#category_filter').on('change', function(){
    var name = $(this).find('option:selected').text();
    var val = $(this).find('option:selected').val();
    $('option:selected', this).remove();
    $('#selected_categories').append('<span class="value" id="'+val+'"><span class="category_name">'+name+'</span><span class="glyphicon glyphicon-remove remove_category"></span></span>');
    filter_recipes();
    $('#selected_categories:has(.value)').find('.selected_title').show();
  });
  $('#selected_categories').on('click', '.remove_category', function(){
    var parent = $(this).parents(".value");
    var name = parent.find('.category_name').text();
    var key = $(this).attr('id');
    $('#category_filter').append($("<option></option>").attr(name, key).text(name));
    parent.remove();
    filter_recipes();
    $('#selected_categories:not(:has(.value))').find('.selected_title').hide();
  });

  $('#component_filter').on('change', function(){
    var name = $(this).find('option:selected').text();
    var val = $(this).find('option:selected').val();
    $('option:selected', this).remove();
    $('#selected_components').append('<span class="value" id="'+val+'"><span class="component_name">'+name+'</span><span class="glyphicon glyphicon-remove remove_component"></span></span>');
    filter_recipes();
    $('#selected_components:has(.value)').find('.selected_title').show();
  });
  $('#selected_components').on('click', '.remove_component', function(){
    var parent = $(this).parents(".value");
    var name = parent.find('.component_name').text();
    var key = $(this).attr('id');
    $('#component_filter').append($("<option></option>").attr(name, key).text(name));
    parent.remove();
    filter_recipes();
    $('#selected_components:not(:has(.value))').find('.selected_title').hide();
  });

  function filter_recipes(){
    var categories = $.map($(".category_name"), function(elem, index){
      return $(elem).text();
    });
    var components = $.map($(".component_name"), function(elem, index){
      return $(elem).text();
    });
    $.ajax({
      url: '/group_filter_recipes',
      data: {
        'categories': categories,
        'components': components
      },
      type: 'post',
      success: function (data) {
        $("#recipes_select option").remove();
        $('#recipes_select').append(new Option('Recipes', ''));
        data.recipes.forEach(function(recipe){
          $('#recipes_select').append(new Option(recipe.name, recipe.id));
        });
      }
    });
  }

  $('#recipes_select').on('change', function(){
    var name = $(this).find('option:selected').text();
    var val = $(this).find('option:selected').val();
    $.ajax({
      url: '/get_recipe_by_id',
      data: {
        'recipe_id': val
      },
      type: 'post',
      success: function(data) {
        var recipe = data.recipe;

        var i = $('#table_meals tr').length - 1;

        var recipe_quantity = $('<input/>', {
          'name': 'group[recipe_quantities_attributes]['+i+'][quantity]',
          'class': 'recipe_quantity',
          'type': 'text',
          'id': 'group_recipe_quantities_attributes_'+i+'_quantity'
        });

        var recipe_quantity_2 = $('<input/>', {
          'name': 'group[recipe_quantities_attributes]['+i+'][recipe_id]',
          'value': recipe.id,
          'type': 'hidden',
          'id': 'group_recipe_quantities_attributes_'+i+'_recipe_id'
        });

        var slider = $('<input/>', {
          'class': 'range',
          'data-slider-id': 'ex1Slider',
          'data-slider-min': '0',
          'data-slider-max': '27',
          'data-slider-value': '0',
          'data-slider-step': '1',
          'type': 'text',
          'value': '0',
          'name': 'group[recipe_quantities_attributes]['+i+'][individuals_served]',
          'id': 'group_recipe_quantities_attributes_'+i+'_individuals_served'
        });

        $('#table_meals tbody').append(
            $('<tr/>', { 'id': recipe.id, 'class': 'block_recipe' }).append(
                $('<td/>', {}).append(recipe_quantity).append(recipe_quantity_2),
                $('<td/>', { 'class': 'recipe_name' }).append(recipe.name),
                $('<td/>', {}).append(slider),
                $('<td/>', {}).append('<a href="">remove</a>')
            ),
            $('<input/>', {
              'type': 'hidden',
              'name': 'group[recipe_quantities_attributes]['+i+'][id]',
              'id': 'group_recipe_quantities_attributes_'+i+'_id'
            })
        );

        $(".range").slider({
          tooltip: 'always',
          formatter: function(value) {
            return value;
          }
        });
      }
    });
  });
});

</script>

app/views/groups/edit.html.erb
<%= render '/layouts/header' %>

<div class="col-md-12 col-sm-12 col-xs-12 inventory_content">
  <h1>EDIT MEAL PLAN</h1>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. <br>
    Proin et porta nunc. In aliquam lacinia ullamcorper.
  </p>
  <%= render 'form' %>
</div>

app/views/groups/index.html.erb
<%= render '/layouts/header' %>

<div class="cont">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="recipes-wrap">
      <h1>My meal plans</h1>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. <br>
        Proin et porta nunc. In aliquam lacinia ullamcorper.
      </p>
      <section class="col-md-12 col-sm-12 col-xs-12">
        <div class="row" style="margin:0;">
          <div class="add-recipe">
            <%= link_to new_group_path do %>
              <span class="plus"></span>
              <span id="span-add">ADD MEAL PLAN</span>
            <% end %>
          </div>
        </div>
      </section>

      <section class="recipes-list">
        <table class="table" >
          <col style="width:75%">
          <col style="width:25%">
          <% @groups.each do |group| %>
            <tr>
              <td><%= link_to group.name, group_path(group.id) %></td>
              <td>
                <%= link_to 'Edit', edit_group_path(group.id) %>
                <span class="devider">/</span>
                <%= link_to 'Delete', '#', class: 'delete_link', 'data-id' => group.id %>
              </td>
            </tr>
          <% end %>
        </table>
      </section>
    </div>
  </div>
</div>

<%= render 'groups/popups/remove_confirmation' %>

<script type="text/javascript">
$(document).ready(function() {
  $("[href='/groups']").addClass("active");

  $('.delete_link').on('click', function(e) {
    e.preventDefault();

    var row = $(this).parents('tr');
    var id = $(this).data('id');

    $('.confirm_button').off('click');
    $('.confirm_button').on('click', function functionName() {
      $.ajax({
        method: 'DELETE',
        url: '<%= groups_path %>' + '/' + id
      }).done(function() {
        row.remove();
      });
    });

    $('#remove_confirmation_Modal').modal();
  });
});

</script>

app/views/groups/new.html.erb
<%= render '/layouts/header' %>

<div class="col-md-12 col-sm-12 col-xs-12 inventory_content">
  <h1>CREATE MEAL PLAN</h1>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. <br>
    Proin et porta nunc. In aliquam lacinia ullamcorper.
  </p>
  <%= render 'form' %>
</div>

app/views/groups/show.html.erb
<%= render '/layouts/header' %>

<div class="col-md-8 col-sm-8 col-xs-8 show-content">
  <h1><%= @group.name %></h1>
  <div class="upper-wrap">
    <div class="total">
      <div>
        <span class="total-label">TOTAL INDIVIDUALS</span>
        <span class="quantity"><%= @group.total_individuals %></span>
      </div>
      <div class="pull-down">
        <span class="total-label">TOTAL SERVINGS</span>
        <span class="quantity"><%= @group.total_servings %></span>
      </div>
      <span><%= @group.description %></span>
    </div>
    <div class="pdf-button">
      <span>DOWNLOAD PDF</span>
    </div>
  </div>
  <div class="small-table">
    <table class="table">
      <colgroup><col style="width:14%">
            <col style="width:40%">
            <col style="width:30%">
            <col style="width:30%">
      </colgroup>
      <thead>
        <tr>
          <td>RECIPE</td>
          <td># of times served</td>
          <td># of individuals served</td>
        </tr>
      </thead>
      <tbody>
      <% @group_recipes.each do |g_recipe| %>
        <tr>
          <td><%= g_recipe.recipe.name %></td>
          <td><%= g_recipe.quantity %></td>
          <td>0</td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="col-md-11 col-sm-11 col-xs-11 show-content">
  <div class="small-table">
  <table class="table text-left">
    <colgroup>
          <col style="width:4%">
          <col style="width:8.5%">
          <col style="width:10.2%">
          <col style="width:13.2%">
          <col style="width:9.8%">
          <col style="width:11%">
          <col style="width:17%">
          <col style="width:14.9%">
          <col style="width:11%">
    </colgroup>
    <thead>
      <tr>
        <td class=""><div class="check-icon">

        </div></td>
        <td>QTY</td>
        <td>UNIT</td>
        <td>ITEM</td>
        <td>STORE</td>
        <td>MEAL(S)</td>
        <td>INVENTORY NOTES</td>
        <td>US</td>
        <td>METRIC</td>
      </tr>
    </thead>
    <tbody>
      <% @ingredients.each do |ingredient| %>
        <tr>
          <td class="checkbox-icon">
            <input type="checkbox" name="checkboxx" id="checkboxx">
            <label for="checkboxx"></label>
          </td>
          <td>30</td>
          <td>Cups</td>
          <td><%= ingredient.name %></td>
          <td><%= ingredient.store %></td>
          <td>
            <span>
              <% ingredient.recipes.in_group(@group.id).each do |recipe| %>
                <%= link_to recipe.name, edit_recipe_path(recipe.id) %>
              <% end %>
            </span>
          </td>
          <td><%= ingredient.note %></td>
          <td>33 g</td>
          <td>33 ml</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>