config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root 'home#index'

  get '/faqs', to: 'home#faqs', as: :faqs
  get '/about_us', to: 'home#about_us', as: :about_us
  get '/contact_us', to: 'home#contact_us', as: :contact_us

  get '/ingredients', to: 'ingredients#index', as: :ingredients
  post '/find_ingredient', to: 'ingredients#find_ingredient', as: :find_ingredient
  post '/update_inventory', to: 'ingredients#update_inventory', as: :update_inventory
  post '/create_price', to: 'ingredients#create_price', as: :create_price
  post '/get_price', to: 'ingredients#get_price', as: :get_price
  post '/get_ingredients_from_usda', to: 'ingredients#get_ingredients_from_usda', as: :get_ingredients_from_usda

  post '/get_units_from_usda', to: 'units#get_units_from_usda', as: :get_units_from_usda
  post '/get_units_by_ingredient', to: 'units#get_units_by_ingredient', as: :get_units_by_ingredient
  post '/create_units', to: 'units#create_units', as: :create_units

  resources :recipes do
    post 'clone'
    get :autocomplete_ingredient_name, on: :collection
  end
  get '/filter_recipes', to: 'recipes#filter_recipes', as: :filter_recipes
  post '/get_type_of_unit', to: 'recipes#get_type_of_unit', as: :get_type_of_unit
  get '/nutrition_label', to: 'recipes#nutrition_label', as: :nutrition_label
  post '/get_recipe_by_id', to: 'recipes#get_recipe_by_id', as: :get_recipe_by_id
  post '/search_tags', to: 'recipes#search_tags', as: :search_tags

  get '/profile', to: 'profile#index', as: :profile
  
  resources :groups
  post '/group_filter_recipes', to: 'groups#filter_recipes', as: :group_filter_recipes
end

app/models/ingredient.rb
# Ingredient model
class Ingredient < ActiveRecord::Base
  belongs_to :user
  has_many :ingredient_quantities,
           class_name: 'RecipeIngredientsQuantity',
           dependent: :destroy
  has_many :recipes, through: :ingredient_quantities
  has_many :usda_units_coefficients, dependent: :destroy
  belongs_to :unit_type
  has_many :ingredient_unit_costs, dependent: :destroy

  validates_presence_of :name, :user, :unit_type

  before_save :squish_name
  around_create :check_for_similar_record

  def get_units
    if unit_type.name == 'USDA'
      ingredient_units = usda_units_coefficients.map(&:unit_id)
      Unit.where(id: ingredient_units)
    else
      unit_type.units
    end
  end

  def create_coefficients
    food = UsdaNutrientDatabase::Food.find_by(nutrient_databank_number: usda_id)
    return if food.blank?
    food.weights.each do |w|
      unit = Unit.find_by(
        name: w.measurement_description,
        unit_type_id: UnitType.find_by(name: 'USDA').id
      )
      coeff = w.amount / w.gram_weight

      UsdaUnitsCoefficient.find_or_create_by(
        ingredient_id: id,
        unit_id: unit.id,
        coefficient: coeff
      )
    end

    gram_unit = Unit.find_by(name: 'gram')
    UsdaUnitsCoefficient.find_or_create_by(
      ingredient_id: id,
      unit_id: gram_unit.id,
      coefficient: 1
    )
  end

  scope :user_id, -> (id) { where(user: id) }
  scope :name_is_like, -> (name) do
    t = arel_table
    where(t[:name].matches(name.squish))
  end

  private

  def squish_name
    name.squish!
  end

  def check_for_similar_record
    ingredient = Ingredient.user_id(user_id).name_is_like(name).first
    if ingredient
      self.id = ingredient.id
      return true
    else
      yield
    end
  end
end

app/controllers/ingredients_controller.rb
# Actions for ingredients page, actions for prices & other actions:
# get_ingredients_from_usda, find_ingredient
class IngredientsController < ApplicationController
  def index
    @ingredients = current_user.ingredients.order(:name).includes(:recipes)
    @recipes = current_user.recipes.order(:name)
    if params[:recipe_id].present?
      @ingredients = Recipe.find_by(id: params[:recipe_id]).ingredients
    end
  end

  def update_inventory
    params[:ingredients].each do |key, value|
      ingredient = Ingredient.find_by(id: key)
      ingredient.update_attributes(
        name: value[:name],
        note: value[:note],
        store: value[:store],
        usda_id: value[:usda_id]
      )
    end
    redirect_to ingredients_path
  end

  def create_price
    unit = Unit.find_by(id: params[:unit_id])
    ingredient = Ingredient.find_by(id: params[:ingredient_id])
    cost = IngredientUnitCost.find_by(
      unit_id: unit.id,
      ingredient_id: ingredient.id
    )
    if cost
      cost.price = params[:price]
      cost.save
    else
      IngredientUnitCost.create(
        unit_id: unit.id,
        ingredient_id: ingredient.id,
        price: params[:price])
    end
    respond_to do |format|
      format.html { redirect_to ingredients_path, notice: 'Price was successfully created.' }
      format.json { render :index, status: :created, location: ingredients_path }
    end
  end

  def get_price
    cost = IngredientUnitCost.find_by(
      unit_id: params[:unit_id],
      ingredient_id: params[:ingredient_id]
    )
    if cost
      render json: { price: cost.price }
    else
      render json: { price: 0 }
    end
  end

  def get_ingredients_from_usda
    ingredients = UsdaNutrientDatabase::Food.includes(:food_group)
    params[:name].split(' ').each do |word|
      ingredients = ingredients.where('short_description ILIKE ?', "%#{word}%")
    end
    render json: { food: ingredients.as_json(include: :food_group) }
  end

  def find_ingredient
    ingredient = Ingredient.user_id(params[:user_id]).name_is_like(params[:ingredient_name]).first
    render json: { ingredient: ingredient, units: ingredient.try(:unit_type).try(:units) }
  end
end

app/views/ingredients/index.html.erb
<%= render '/layouts/header' %>
<div class="col-md-12 col-sm-12 col-xs-12 inventory_content">
  <h1>INGREDIENTS</h1>
  <p>
    Below you'll find a list of ingredients used in your recipes. <br>
    You can filter list by recipes or edit ingredients to include <br>
	  cost estimates or USDA Nutrient Database information.
  </p>

  <div class="col-md-10 col-sm-10 col-centered col-centered">
    <%= form_tag  ingredients_path, method: :get do %>
      <div class="filters">
        <div class="select-wrapper">
          <%= select_tag 'recipe_id', options_for_select(@recipes.all.collect{ |c| [c.name, c.id] }, params[:recipe_id]), include_blank: 'All recipes', id: 'recipe_select' %>
        </div>
      </div>
    <% end %>

    <%= form_tag update_inventory_path, method: :post do %>
      <div class="recipe-form">
        <table id="table_ingredients" class="table ingredients">
            <col style="width:14%">
            <col style="width:21%">
            <col style="width:13%">
            <col style="width:9%">
            <col style="width:14%">
            <col style="width:13%">
            <col style="width:16%">
          <thead>
            <tr>
              <th>ITEM</th>
              <th>INVENTORY & PURCHASING NOTES</th>
              <th>MEALS</th>
              <th>STORE</th>
              <th>USDA NUTRIENT DATA</th>
              <th>COST ESTIMATES</th>
            </tr>
          </thead>
          <tbody id="ingredients">
            <% for ingredient in @ingredients %>
              <%= fields_for 'ingredients[]', ingredient do |f| %>
                <tr id="<%= ingredient.id %>">
                  <td>
                    <%= f.text_field :name, class: 'ingredient_name' %>
                  </td>

                  <%= f.hidden_field :unit_type_id, { value: f.object.unit_type_id, class: 'unit_type' } %>

                  <td>
                    <%= f.text_field :note %>
                  </td>
                  <td>
                    <span>
                      <% ingredient.recipes.each do |recipe| %>
                        <%= link_to recipe.name+" ,", edit_recipe_path(recipe.id) %>
                      <% end %>
                    </span>
                  </td>
                  <td>
                    <%= f.text_field :store %>
                  </td>
                  <td>
                    <button type="button" name="button" class="glass" data-toggle="modal" data-target="#nutrient_Modal"
                            <% if f.object.usda_id %>style="background-color:#C3D1C7;border-radius:3px"<% end %>>
                    </button>
                    <%= f.hidden_field :usda_id, { value: f.object.usda_id, class: 'ingredient_usda_id' } %>
                  </td>
                  <td>
                    <button type="button" name="button" class="calc" id="ingredient_costs" data-toggle="modal" data-target="#calc_Modal"></button>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
      <%= submit_tag 'SAVE CHANGES', id: 'inventory_submit', class: 'submit-button', disabled: true %>
    <% end %>
  </div>
</div>

<%= render 'ingredients/popups/costs' %>
<%= render 'recipes/usda_ingredients' %>

<script type="text/javascript">
$(document).ready(function(){
  $("[href='/ingredients']").addClass("active");
////////////////////////// ENABLE\DISABLE SAVE BUTTON //////////////////
  $('#table_ingredients').on('change','input, select',function traceChange(){
    $("#inventory_submit").prop('disabled',false);
    $("#inventory_submit").hover(function(){
        $(this).css("background-color", "#19462f");
      },function(){
        $(this).css("background-color", '#515B42');
      });
  });

//////////////////////////  COSTS MODAL ////////////////////////////////
  $(".ingredients").on("click", "#ingredient_costs", function() {
    if ($("#price_input").val() == "") {
      $("#dolar_sign").css("color", "#B5B5B5");
    } else {
      $("#dolar_sign").css("color", "black");
    }

    $('#price_ingredient_id').val($(this).closest('tr').attr('id'));
    $('#select_price_unit').find('option').remove().end();
    var ingredient_name = $(this).closest('tr').find('.ingredient_name').val();

    $.ajax({
      url: '/get_units_by_ingredient',
      data: {
        'ingredient_name': ingredient_name
      },
      type: 'post',
      success: function (data) {
        for (var i in data.units) {
          $('#select_price_unit').append(new Option(data.units[i].name, data.units[i].id));
        }
        $('#select_price_unit').val(data.units[0].id);
        $('#select_price_unit').trigger('change');
      }
    });

    $(".submit-button").on("click", function(e) {
      e.preventDefault();
      $('#create_price_form').submit();
      $('#calc_Modal').modal('hide');
    });
  });
});

/////////////////////////////// FILTERING /////////////////////////////////
  $("#recipe_select").change(function() {
    $(this).parents("form").submit();
  });
</script>