config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root 'home#index'

  get '/faqs', to: 'home#faqs', as: :faqs
  get '/about_us', to: 'home#about_us', as: :about_us
  get '/contact_us', to: 'home#contact_us', as: :contact_us

  get '/ingredients', to: 'ingredients#index', as: :ingredients
  post '/find_ingredient', to: 'ingredients#find_ingredient', as: :find_ingredient
  post '/update_inventory', to: 'ingredients#update_inventory', as: :update_inventory
  post '/create_price', to: 'ingredients#create_price', as: :create_price
  post '/get_price', to: 'ingredients#get_price', as: :get_price
  post '/get_ingredients_from_usda', to: 'ingredients#get_ingredients_from_usda', as: :get_ingredients_from_usda

  post '/get_units_from_usda', to: 'units#get_units_from_usda', as: :get_units_from_usda
  post '/get_units_by_ingredient', to: 'units#get_units_by_ingredient', as: :get_units_by_ingredient
  post '/create_units', to: 'units#create_units', as: :create_units

  resources :recipes do
    post 'clone'
    get :autocomplete_ingredient_name, on: :collection
  end
  get '/filter_recipes', to: 'recipes#filter_recipes', as: :filter_recipes
  post '/get_type_of_unit', to: 'recipes#get_type_of_unit', as: :get_type_of_unit
  get '/nutrition_label', to: 'recipes#nutrition_label', as: :nutrition_label
  post '/get_recipe_by_id', to: 'recipes#get_recipe_by_id', as: :get_recipe_by_id
  post '/search_tags', to: 'recipes#search_tags', as: :search_tags

  get '/profile', to: 'profile#index', as: :profile
  
  resources :groups
  post '/group_filter_recipes', to: 'groups#filter_recipes', as: :group_filter_recipes
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="cont">
    <div class="col-md-4 col-sm-3 section logo-footer">
      <div class="row">
        <div class="logo">
          <%= link_to root_path do %>
            <%= image_tag 'logo.png' %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-2 col-sm-3 col-xs-4 section">
      <div class="row">
        <nav class="footer-menu" id="menu">
          <ul class="nav navbar-nav navbar-left menu">
            <li><a href="#">About Us</a></li>
            <li><a href="#">FAQs</a></li>
            <li><a href="#">Contact Us</a></li>
          </ul>
        </nav>
      </div>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-4 section">
      <div class="row">
        <div class="help">
          <span>HELP &amp; CONTACT</span>
          <a href="#" class="contants"><span>i</span>Email Support</a>
        </div>
      </div>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-4 section">
      <div class="row">
        <p class="linkup">
          Developing by<br>
          LinkUp Studio
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header all-page">
  <% if user_signed_in? %>
    <div class="top-section">
      <div class="cont">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <span>Your trial will expire in 29 days.</span>
          <div class="user_signed_in">
            <ul class="nav navbar-nav navbar-left menu">
              <li><%= link_to 'MY PROFILE', profile_path %></li>
              <li><%= link_to 'LOG OUT', destroy_user_session_path, method: :delete %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="cont">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="row">
        <button type="button" id="mob-menu" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <nav class="main-menu collapse navbar-collapse" id="menu">
          <ul class="nav navbar-nav navbar-left menu">
            <li><%= link_to 'About Us', about_us_path %></li>
            <li><%= link_to 'FAQs', faqs_path %></li>
            <li><%= link_to 'Contact Us', contact_us_path %></li>
            <li><a href="http://blog.wholesumfoodcalc.com">Blog</a></li>
          </ul>
          <div class="login_buttons">
              <ul class="nav navbar-nav menu">
            <% if user_signed_in? %>
              <li><%= link_to 'My recipes', recipes_path %></li>
              <li><%= link_to 'Ingredients', ingredients_path %></li>
              <li><%= link_to 'Meal plans', groups_path %></li>
            <% else %>
                <li><%= link_to 'Log in', new_user_session_path %></li>
                <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <% end %>
              </ul>
          </div>
        </nav>
        <div id="logo" class="logo">
          <%= link_to root_path do %>
            <%= image_tag 'logo.png' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</header>

<script type="text/javascript">
  $(document).ready(function() {
    if($(window).width()<768){
      $("#logo").after($("#menu"));
    }
    $(window).resize(function() {
      if($(window).width()<768){
        $("#logo").after($("#menu"));
      }
      else{
        $("#logo").before($("#menu"));
      }
    });
  });
</script>

app/views/layouts/_home_header.html.erb
<header class="header home">
  <% if user_signed_in? %>
    <div class="top-section">
      <div class="cont">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <span>Your trial will expire in 29 days.</span>
          <div class="user_signed_in">
            <ul class="nav navbar-nav navbar-left menu">
              <li><%= link_to 'MY PROFILE', profile_path %></li>
              <li><%= link_to 'LOG OUT', destroy_user_session_path, method: :delete %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="cont">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="row">
        <button type="button" id="mob-menu" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <nav class="main-menu collapse navbar-collapse" id="menu">
          <ul class="nav navbar-nav navbar-left menu">
            <li><%= link_to 'About Us', about_us_path %></li>
            <li><%= link_to 'FAQs', faqs_path %></li>
            <li><%= link_to 'Contact Us', contact_us_path %></li>
            <li><a href="http://blog.wholesumfoodcalc.com">Blog</a></li>
          </ul>
          <div class="login_buttons">
              <ul class="nav navbar-nav menu">
            <% if user_signed_in? %>
                <li><a href="/recipes">My recipes</a></li>
                <li><a href="/ingredients">Ingredients</a></li>
                <li><a href="<%= groups_path %>">Meal plans</a></li>
            <% else %>
                <li><%= link_to 'Log in', new_user_session_path %></li>
                <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <% end %>
              </ul>
          </div>
        </nav>
        <div id="logo" class="logo">
          <%= link_to root_path do %>
            <%= image_tag 'logo.png' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</header>

<script type="text/javascript">
  $(document).ready(function() {
    if($(window).width()<768){
      $("#logo").after($("#menu"));
    }
    $(window).resize(function() {
      if($(window).width()<768){
        $("#logo").after($("#menu"));
      }
      else{
        $("#logo").before($("#menu"));
      }
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wholesum</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0,target-densitydpi=device-dpi, user-scalable=no">

</head>
<body>
  <div class="wrap">
    <% if flash[:notice].present? %>
      <div class="modal message fade" id="notice-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header" style="border-bottom: none">
              <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button> -->
            </div>
            <div class="modal-body" style="text-align: center">
              <%= flash[:notice] %>
            </div>
            <div class="modal-footer" style="border-top: none">
              <!-- <button type="button" id="notice-btn" class="btn btn-default" data-dismiss="modal">OK</button> -->
            </div>
          </div>
        </div>
      </div>
      <script type="text/javascript">
        $("#notice-modal").modal("show");
      </script>
    <% end %>
    <% if flash[:alert].present? %>
      <div class="modal message fade" id="alert-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header" style="border-bottom: none">
              <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button> -->
            </div>
            <div class="modal-body" style="text-align: center">
              <%= flash[:alert] %>
            </div>
            <div class="modal-footer" style="border-top: none">
              <!-- <button type="button" id="notice-btn" class="btn btn-default" data-dismiss="modal">OK</button> -->
            </div>
          </div>
        </div>
      </div>
      <script type="text/javascript">
        $("#alert-modal").modal("show");
      </script>
    <% end %>

    <%= yield %>
    <%= render '/layouts/footer' %>
  </div>
</body>
</html>